# deploy IPFS from pre-build docker image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-kube-gateway
  labels:
    app: ipfs-kube-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipfs-kube-gateway
  template:
    metadata:
      labels:
        app: ipfs-kube-gateway
    spec:
      containers:
        - name: ipfs
          image: 'samperfect/ipfs-node:v5.6'
          ports:
            - name: swarm
              protocol: TCP
              containerPort: 4001
            - name: http
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: swarm
            initialDelaySeconds: 30
            timeoutSeconds: 100
            periodSeconds: 15
          # readinessProbe:
          #   httpGet:
          #     path: /ipfs/QmcDge1SrsTBU8b9PBGTGYguNRnm84Kvg8axfGURxqZpR1
          #     port: http
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 300
          #   periodSeconds: 15
          resources:
            requests:
              memory: '500Mi'
              cpu: '1000m'
              ephemeral-storage: '2Gi'
            limits:
              memory: '1Gi'
              cpu: '2000m'
              ephemeral-storage: '5Gi'

          # command: ['stress']
          # args: ['--vm', '1', '--vm-bytes', '500M', '--vm-hang', '1']
      #     volumeMounts:
      #       - name: ipfs-storage
      #         mountPath: /data/ipfs
      #     resources: {}

      # volumes:
      #   - name: ipfs-storage
      #     emptyDir: {}
